### ISSUE TITLE
Error in webtrees 2.1.0-dev

### ISSUE THREAD

**Issue by melizaa** [vytux-com/vytux_cousins#12]
app/Gedcomcode/GedcomCodePedi.php was removed from webtrees.

We get now error
Class 'Fisharebest\Webtrees\GedcomCode\GedcomCodePedi' not found …/modules_v4/vytux_cousins/module.php:219

**Comment by melizaa** [comment]
Now I see
Class 'Fisharebest\Webtrees\GedcomCode\GedcomCodePedi' not found …/modules_v4/vytux_cousins/module.php:224

**Comment by geugeu1** [comment]
The module is throwing an error when upgrading site to 2.1.0 of webtrees.

**Comment by vytux-com** [comment]
I hope to be able to have a look at converting it to support 2.1 in a couple of weeks time. I'm currently migrating servers and need to get my test systems online again.
