### ISSUE TITLE
The error of vytux-cousins module in webtrees 2 1.0 

### ISSUE THREAD

**Issue by iyoua** [vytux-com/vytux_cousins#17]
I like the vytux cousins module very much, but after webtrees is upgraded to 2.1.0, this module makes mistakes.
Will you update this module? I hope you can come back!
Best wishes

**Comment by vytux-com** [comment]
I hope to be able to have a look at converting it to support 2.1 in a couple of weeks time. I'm currently migrating servers and need to get my test systems online again.
