### ISSUE TITLE
Installation of module - rename folder

### ISSUE THREAD

**Issue by jpretired** [vytux-com/vytux_cousins#19]
After unzipping the module folder must be renamed to "vytux_cousins" (without the version ending).

**Comment by vytux-com** [comment]
Yeah, I need to see if there is a way to create a release on GitHub without the version number.

**Comment by vytux-com** [comment]
Reading up on the way GitHub releases work i basically need to upload my own version of the Zip file as the auto generated one is always a little funky. Sounds like a silly system, but I'll keep that in mind for future releases.

I have updated the last release to include this modified zip
