### ISSUE TITLE
Cousins tab layout - two columns

### ISSUE THREAD

**Issue by jpretired** [vytux-com/vytux_cousins#20]
In version 1.x the cousins were displayed in two columns - left father's family, right mother's family. Needless to say this was much better arranged layout.
Is it possible to apply this in version 2.x?

**Comment by vytux-com** [comment]
That has not changed, I think it's based on the size of the screen it's being shown on. Much like the rest of webtrees, once the screen size goes below a certain size it switches to mobile view and single column.

**Comment by jpretired** [comment]
I think something has been changed, as my webtrees site is set to max size screen,
see: https://test.jprodina.cz/tree/tree1/individual/I112/Augustin-Prause#tab-_vytux_cousins_

**Comment by vytux-com** [comment]
Oh you are right, something has changed in the webtress 2.1 release I guess. Let me see if I can see why this is now always in single  column.

**Comment by jpretired** [comment]
Now it works ok, good job, vitautas.
Incredible - such an influence of one single "c" of millions of them!
