### ISSUE TITLE
Small update needed for latest code.

### ISSUE THREAD

**Issue by fisharebest** [vytux-com/vytux_cousins#3]
In your `boot()` method, you type-hint two variables - `$user` and `$tree`.

https://github.com/vytux-com/vytux_cousins/blob/master/module.php#L262
1) You do not use these variables so you do not need to specify them

2) In the latest code, you cannot request the tree like this.  Instead, you obtain it as an attribute of the request. `$request->getAttribute('tree')`.

**Comment by vytux-com** [comment]
Thanks, fixed in 0de66a5

**Comment by melizaa** [comment]
Works now as expected. Thanks
