### ISSUE TITLE
The webtrees cousins module gives again an error - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [vytux-com/vytux_cousins#4]
I get again an error in webtrees 2.0.0

Call to undefined method Fisharebest\Webtrees\Individual::primaryChildFamily() …/modules_v4/vytux_cousins/module.php:159
#0 …/modules_v4/vytux_cousins/module.php(238): Vytux\WebtreesModules\VytuxCousins\VytuxCousinsTabModule->getCousins(Object(Fisharebest\Webtrees\Individual))
#1 …/resources/views/individual-page.phtml(120): Vytux\WebtreesModules\VytuxCousins\VytuxCousinsTabModule->getTabContent(Object(Fisharebest\Webtrees\Individual))
#2 …/app/View.php(186): include('/home/amitys/te...')
#3 …/app/View.php(282): Fisharebest\Webtrees\View->render()
#4 …/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make('individual-page', Array)
#5 …/app/Http/ViewResponseTrait.php(51): view('individual-page', Array)
#6 …/app/Http/RequestHandlers/IndividualPage.php(171): Fisharebest\Webtrees\Http\RequestHandlers\IndividualPage->viewResponse('individual-page', Array)
#7 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\IndividualPage->handle(Object(Nyholm\Psr7\ServerRequest))
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#9 …/app/Module/HitCountFooterModule.php(147): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
etc.

**Comment by fisharebest** [comment]
Hi Vytux,

There has been a small change in the 2.0.0 release.

Instead of `Individual::primaryChildFamily()` we now use `Individual::childFamilies()->first()`

This is because there is no longer any special logic to choose the "primary" family.
We now use the first family in the GEDCOM record.  This allows users to control which family is the "primary" one.

Greg

**Comment by vytux-com** [comment]
Fixed
