### ISSUE TITLE
I see another error in cousins - wt 2.0.0

### ISSUE THREAD

**Issue by melizaa** [vytux-com/vytux_cousins#5]
now I get
Call to undefined method Fisharebest\Webtrees\Individual::getLifeSpan() …/modules_v4/vytux_cousins/resources/views/tab.phtml:25
#0 …/app/View.php(186): include()
#1 …/app/View.php(282): Fisharebest\Webtrees\View->render()
#2 …/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make('_vytux_cousins_...', Array)
#3 …/modules_v4/vytux_cousins/module.php(240): view('_vytux_cousins_...', Array)
#4 …/resources/views/individual-page.phtml(120): Vytux\WebtreesModules\VytuxCousins\VytuxCousinsTabModule->getTabContent(Object(Fisharebest\Webtrees\Individual))
#5 …/app/View.php(186): include('/home/amitys/te...')
#6 …/app/View.php(282): Fisharebest\Webtrees\View->render()
#7 …/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make('individual-page', Array)
etc.

**Comment by fisharebest** [comment]
This function was renamed from `getLifeSpan()` to `lifespan()`.

In general, we only need `getXXX()` when there is also `setXXX()`.

**Comment by vytux-com** [comment]
Fixed
