### ISSUE TITLE
Translation?

### ISSUE THREAD

**Issue by jpretired** [vytux-com/vytux_cousins#7]
In webtrees 1.7 there were .mo files in language folder.
Could you please describe, say in README.md, how to implement translation into a language without modifying your module.php?

**Comment by vytux-com** [comment]
If you are not sure how to convert it to the new PHP style translation just send the the po file and I will convert it and add it to the next release

**Comment by jpretired** [comment]
Here it is (hopefully).
Thank you
[vytux_cousins-po-mo.zip](https://github.com/vytux-com/vytux_cousins/files/4107789/vytux_cousins-po-mo.zip)

**Comment by vytux-com** [comment]
Could you please try the latest commit to confirm that the translation is working as expected.

**Comment by jpretired** [comment]
Yes, the translation is working OK, thank you.
But there is an issue, see https://github.com/vytux-com/vytux_cousins/issues/8.
