### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by arbor95** [vytux-com/vytux_cousins#9]
I am missing the translation of some items.
I use webtrees with german language.
thx Franz

**Comment by vytux-com** [comment]
I would need someone to provide me with the German translation.

You could either send me the translated strings or make a PR with the changes required.

The strings can be found in one of the already translated functions at the bottom of module.php

**Comment by arbor95** [comment]
you can pull!

**Comment by vytux-com** [comment]
Merged the request
